---
# Configure Wordpress

- name: Download Wordpress and unzip it
  unarchive:
    src: "{{ nextcloud_url }}"
    dest: /var/www/html/
    remote_src: yes

- name: nextcloud data folder
  file:
    path: /var/www/html/nextcloud/data
    state: directory
    mode: '0755'

- name: Recursively change ownership nextcloud directory
  file:
    path: /var/www/html/nextcloud/
    state: directory
    recurse: yes
    owner: apache
    group: apache
  notify:
  - restart apache